version: '3.8'

services:
  # Database Service (Development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: friendly-i-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: friendlyi_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - friendly-i-dev-network

  # Redis Service (Development)
  redis-dev:
    image: redis:7-alpine
    container_name: friendly-i-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"
    networks:
      - friendly-i-dev-network

  # Backend Application (Development)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: friendly-i-backend-dev
    restart: unless-stopped
    depends_on:
      - postgres-dev
      - redis-dev
    environment:
      # Spring Profile
      SPRING_PROFILES_ACTIVE: dev
      
      # Server Configuration
      SERVER_PORT: 8080
      
      # Database Configuration
      DB_HOST: postgres-dev
      DB_PORT: 5432
      DB_NAME: friendlyi_dev
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_password
      
      # Redis Configuration
      REDIS_HOST: redis-dev
      REDIS_PORT: 6379
      
      # JWT Configuration (Development keys)
      JWT_SECRET: dev-jwt-secret-key-for-development-only
      JWT_EXPIRATION: 86400000
      
      # Debug Configuration
      JAVA_OPTS: "-Xms256m -Xmx512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./backend/src:/app/src:ro
      - backend_dev_uploads:/app/uploads
      - backend_dev_logs:/app/logs
    ports:
      - "8081:8080"  # Different port for dev
      - "5005:5005"  # Debug port
    networks:
      - friendly-i-dev-network
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]

# Volumes
volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  backend_dev_uploads:
    driver: local
  backend_dev_logs:
    driver: local

# Networks
networks:
  friendly-i-dev-network:
    driver: bridge
    name: friendly-i-dev-network